### ISSUE TITLE
Nodemon dependency out of date

### ISSUE THREAD

**Issue by NullDivision** [ChrisWren/grunt-nodemon#64] opened 2015-10-07 16:23 UTC
The nodemon package is out of date as a dependency. Current working version is `v1.7.1` which has some dependencies that cause breakage in some scenarios.

For example:

In the event that the user tries to install `grunt-nodemon` as a dependency alongside `mongoose`, `grunt-nodemon` will require `nodemon` who requires `touch`. The version in the current dependency stack is `v1.3.8` which brings `touch` 0.0.4. The current dependency is `touch` 1.0.0.

**Comment by mgoldsborough** [comment] 2015-10-14 20:17
@NullDivision, I had the same problem. I just forked, updated and published v0.5.0 here:

https://www.npmjs.com/package/grunt-contrib-nodemon

**Comment by NullDivision** [comment] 2015-10-14 20:53
If you fork you should probably make an even effort dude. Check pull request #65 for a proper fix.

**Comment by mgoldsborough** [comment] 2015-10-14 21:33
The problem is that https://github.com/remy/nodemon doesn't specific a version in their package.json so tools like [outdated](https://docs.npmjs.com/cli/outdated) don't pick it up.  I just bumped nodemon to v1.7.1.

Either way, use it or don't but no need to be so abrasive.

**Comment by NullDivision** [comment] 2015-10-14 22:31
NPM-s versioning behavior relies on git tags if present so explicit version declarations (while useful) aren't mandatory.

I'm abrasive because:
- you basically sed replaced all mentions of the original author name/repo with your own own
- you hotfixed touch but left all other dependencies untouched
- you removed the mdlint requirement (not a bad point but it's there)
- bumped a minor version for something that's basically a patch
- didn't even bother to do a pull request for the original author

I already did this a week ago for my own project. If your intention was to do take over the project, at least make an effort is what I'm saying.

**Comment by mgoldsborough** [comment] 2015-10-14 23:55
#66

**Comment by mlarcher** [comment] 2015-11-29 18:09
@ChrisWren Could you pleas update the nodemon version pulled by grunt-nodemon ? Amon other problems, the currently imported version has big performance issues when running in git-bash (cf https://github.com/remy/nodemon/issues/624 )
I see a PR is already ready, so why not merge it ?

**Comment by ChrisWren** [comment] 2015-12-01 16:25
Sorry, just merged

**Closed by ChrisWren** 2015-12-01 16:25 UTC
